<?php

$sql =<<<EOF
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_addad` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) DEFAULT NULL,
  `rid` int(10) NOT NULL DEFAULT '0',
  `rulename` varchar(255) NOT NULL COMMENT '活动规则',
  `adlogo` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告图片',
  `adtitle` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告标题',
  `addetails` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告简介',
  `adlink` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告链接',
  `createtime` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0表示未投放，1表示投放',
  PRIMARY KEY (`id`),
  KEY `idx_id_rulename` (`id`,`rulename`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_award` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `weid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `turntable` int(3) unsigned NOT NULL COMMENT '类型，现场抽奖1，抢红包2',
  `title` varchar(50) NOT NULL COMMENT '奖项',
  `total` int(11) NOT NULL COMMENT '数量',
  `probalilty` varchar(5) NOT NULL COMMENT '概率',
  `description` varchar(100) NOT NULL DEFAULT '' COMMENT '描述',
  `credit` int(10) NOT NULL,
  `card_id` varchar(255) NOT NULL,
  `fansID` int(11) DEFAULT '0',
  `jifen` int(10) NOT NULL COMMENT '获得的积分',
  `from_user` varchar(50) DEFAULT '0' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `iszhuangyuan` tinyint(1) NOT NULL DEFAULT '0',
  `titleid` int(10) NOT NULL COMMENT '奖项的id',
  `awardname` varchar(50) DEFAULT '' COMMENT '描述',
  `prizetype` varchar(10) DEFAULT '' COMMENT '类型，0表示红包，1表示卡券，2表示实物',
  `awardsimg` varchar(200) NOT NULL COMMENT '奖品图片',
  `prize` int(11) DEFAULT '0' COMMENT '奖品排序，数字越大拍越靠前',
  `hbpici` int(4) DEFAULT '0',
  `createtime` int(10) DEFAULT '0',
  `consumetime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_createtime` (`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_bpadmin` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `bpadmin` int(3) unsigned NOT NULL COMMENT '类型，bp，ds',
  `status` int(3) unsigned NOT NULL COMMENT '启用',
  `free_times` int(3) unsigned NOT NULL COMMENT '免费次数',
  `uses_times` int(3) unsigned NOT NULL COMMENT '使用次数',
  `admin_name` varchar(255) NOT NULL COMMENT '管理员名称',
  `admin_mobile` varchar(255) NOT NULL COMMENT '管理员电话',
  `admin_openid` text NOT NULL COMMENT '管理员openid',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  `set_hb` int(3) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_bpmoney` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `bp_money` decimal(11,2) DEFAULT '0.00' COMMENT '霸屏金额',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启',
  `bp_time` int(10) NOT NULL DEFAULT '0' COMMENT '霸屏时间',
  `createtime` int(11) DEFAULT '0' COMMENT '创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_bpreply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `isbp` tinyint(1) DEFAULT '0' COMMENT '是否开启霸屏活动',
  `isds` tinyint(1) DEFAULT '0' COMMENT '是否开启打赏活动',
  `isbd` tinyint(1) DEFAULT '0' COMMENT '是否开启榜单',
  `ishb` tinyint(1) DEFAULT '0' COMMENT '是否开启发红包',
  `isvo` tinyint(1) DEFAULT '0' COMMENT '是否开启小视频',
  `ismbp` tinyint(1) DEFAULT '0' COMMENT '是否开启手机顶部霸屏',
  `ispmd` tinyint(1) DEFAULT '0' COMMENT '是否开启跑马灯',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '霸屏消息是否审核',
  `bp_pay` tinyint(1) NOT NULL DEFAULT '0' COMMENT '霸屏支付方式，0，1',
  `bp_pay2` tinyint(1) NOT NULL DEFAULT '0' COMMENT '霸屏支付方式，0，1',
  `bp_maxnum` int(10) NOT NULL DEFAULT '0' COMMENT '每天免费霸屏次数',
  `bp_bg` varchar(300) DEFAULT '' COMMENT '背景图片',
  `bp_title` varchar(300) DEFAULT '' COMMENT '大屏幕标题',
  `bp_img` varchar(300) DEFAULT '' COMMENT '封面',
  `bp_music` varchar(300) DEFAULT '' COMMENT '背景音乐',
  `bp_voice` varchar(300) DEFAULT '' COMMENT '霸屏音乐',
  `bp_keyword` text NOT NULL COMMENT '禁止关键字',
  `bp_listword` text NOT NULL COMMENT '屏蔽关键字',
  `bd_endtime` int(11) DEFAULT '0' COMMENT '报名结束时间',
  `bd_starttime` int(10) DEFAULT '0' COMMENT '报名开始时间',
  `createtime` int(11) DEFAULT '0' COMMENT '创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_cardticket` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `weid` int(10) DEFAULT NULL,
  `createtime` varchar(20) DEFAULT NULL,
  `ticket` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_cash` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `fansID` int(11) DEFAULT '0',
  `from_user` varchar(50) DEFAULT '0' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `awardname` varchar(50) DEFAULT '' COMMENT '兑奖金额',
  `prizetype` varchar(10) DEFAULT '' COMMENT '类型',
  `awardsimg` varchar(200) NOT NULL COMMENT '奖品图片',
  `prize` int(11) DEFAULT '0' COMMENT '奖品ID',
  `credit` int(11) DEFAULT '0' COMMENT '奖品金额',
  `createtime` int(10) DEFAULT '0',
  `consumetime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_cjxreply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `isCjxStart` tinyint(1) DEFAULT '0' COMMENT '是否开启抽奖',
  `isCjxcjnum` tinyint(1) DEFAULT '0' COMMENT '同一个人中奖数量',
  `cjxBg` varchar(255) DEFAULT '',
  `cjxMusic` varchar(255) DEFAULT '',
  `cjxVideo` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `fromuser` varchar(50) NOT NULL DEFAULT '' COMMENT '分享人openid',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
  `visitorstime` int(10) unsigned NOT NULL COMMENT '访问时间',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '查看次数',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_fromuser` (`fromuser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_draw_default` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL,
  `turntable` int(3) unsigned NOT NULL COMMENT '类型，现场抽奖1，抢红包2',
  `rulename` varchar(255) NOT NULL COMMENT '活动规则',
  `openid` varchar(50) DEFAULT '' COMMENT '用户ID',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
  `realname` varchar(20) NOT NULL,
  `mobile` varchar(11) NOT NULL,
  `prizename` varchar(30) NOT NULL,
  `status` tinyint(1) NOT NULL,
  `fansid` int(10) DEFAULT '0',
  `prizeid` int(10) DEFAULT '0',
  `creattime` int(10) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_ds_pay_order` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `orderid` varchar(30) DEFAULT '0' COMMENT '订单单号',
  `transid` varchar(30) DEFAULT '0' COMMENT '微信支付单号',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT 'openid',
  `ds_openid` varchar(50) NOT NULL DEFAULT '' COMMENT '打赏人openid',
  `from_realname` varchar(50) NOT NULL DEFAULT '' COMMENT '名字',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `message` varchar(150) NOT NULL DEFAULT '' COMMENT '打赏留言',
  `pay_ip` varchar(15) NOT NULL DEFAULT '' COMMENT '支付IP',
  `pay_addr` varchar(50) NOT NULL DEFAULT '' COMMENT '地理位置',
  `pay_total` decimal(11,2) DEFAULT '0.00' COMMENT '支付金额',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '下单未付款1已付款2已关闭3',
  `pay_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0表示报名，1表示打赏，2表示霸屏',
  `fansid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '签到fansID',
  `createtime` int(11) unsigned NOT NULL COMMENT '创建时间',
  `paytime` int(11) unsigned NOT NULL COMMENT '支付时间',
  `txlogid` int(11) unsigned NOT NULL COMMENT '提现ID',
  `closetime` int(11) unsigned NOT NULL COMMENT '关闭时间',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_status` (`status`),
  KEY `indx_pay_total` (`pay_total`),
  KEY `indx_transid` (`transid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_ds_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `title` varchar(50) DEFAULT '',
  `description` varchar(255) DEFAULT '',
  `start_picurl` varchar(200) DEFAULT '',
  `backpicurl` varchar(200) DEFAULT '',
  `backcolor` varchar(200) DEFAULT '',
  `starttime` int(10) DEFAULT '0',
  `endtime` int(10) DEFAULT '0',
  `tiemadpic` varchar(200) DEFAULT '',
  `timead` int(10) DEFAULT '0',
  `timenum` int(10) DEFAULT '0',
  `viewnum` int(10) DEFAULT '0',
  `fansnum` int(10) DEFAULT '0',
  `split_money` int(10) DEFAULT '0',
  `split_date` int(10) DEFAULT '0',
  `is_ziliao` tinyint(10) DEFAULT '0',
  `timeadurl` varchar(255) DEFAULT '0',
  `noip_url` varchar(255) DEFAULT '0',
  `share_url` varchar(255) DEFAULT '0',
  `ruleimg_url` varchar(255) DEFAULT '0',
  `ad_link` varchar(255) DEFAULT '0',
  `zhuanfaimg` varchar(255) DEFAULT '0',
  `counter_fee` varchar(20) DEFAULT '0.00' COMMENT '打赏总金额',
  `is_openbbm` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '不开启0，开启1',
  `share_imgurl` varchar(255) NOT NULL COMMENT '分享朋友或朋友圈图',
  `share_title` varchar(200) DEFAULT '',
  `share_desc` varchar(300) DEFAULT '',
  `share_link` varchar(300) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_fans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rid` int(11) DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `fansID` int(11) DEFAULT '0',
  `from_user` varchar(50) DEFAULT '' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '联系地址',
  `qdword` varchar(155) NOT NULL DEFAULT '' COMMENT '签到祝福语',
  `today_most_times` int(11) DEFAULT '0' COMMENT '每日最多次数',
  `sharenum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分享量',
  `sharetime` int(10) DEFAULT '0' COMMENT '提现次数',
  `awardingid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '兑奖地址ID',
  `sex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '性别',
  `todaynum` int(11) DEFAULT '0',
  `totalnum` int(11) DEFAULT '0',
  `hbpici` int(4) DEFAULT '0',
  `jifen` int(10) NOT NULL COMMENT '总积分',
  `tp_times` int(10) DEFAULT '0' COMMENT '投票次数',
  `isbaoming` tinyint(1) DEFAULT '0' COMMENT '是否报名过了',
  `awardnum` int(11) DEFAULT '0',
  `qhb_awardnum` int(11) DEFAULT '0',
  `last_time` int(10) DEFAULT '0',
  `zhongjiang` tinyint(1) DEFAULT '0',
  `is_back` tinyint(1) DEFAULT '0',
  `createtime` int(10) DEFAULT '0',
  `fanshbnum` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_mobile` (`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_guest` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `turntable` int(3) unsigned NOT NULL COMMENT '类型，打赏项目1，打赏礼物2',
  `sort` int(3) unsigned NOT NULL COMMENT '排序',
  `ds_time` int(3) unsigned NOT NULL COMMENT '时间',
  `name` varchar(50) NOT NULL COMMENT '名称',
  `pic` varchar(255) NOT NULL COMMENT '手机图片',
  `ds_pic` varchar(255) NOT NULL COMMENT '大屏幕图片',
  `ds_vodiobg` varchar(300) NOT NULL COMMENT '大屏幕视频',
  `says` text NOT NULL COMMENT '打赏说明',
  `price` decimal(11,2) NOT NULL COMMENT '打赏金额',
  `type` tinyint(1) DEFAULT '0' COMMENT '打赏次数',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_turntable` (`turntable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_hb` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) unsigned NOT NULL DEFAULT '0',
  `set` text,
  `mchid` varchar(100) NOT NULL DEFAULT '' COMMENT '商户号',
  `password` varchar(250) NOT NULL DEFAULT '' COMMENT '商户密码',
  `appid` varchar(100) NOT NULL DEFAULT '' COMMENT '服务号ID',
  `secret` varchar(255) NOT NULL DEFAULT '' COMMENT '服务号secret',
  `ip` varchar(100) NOT NULL DEFAULT '' COMMENT '服务器IP',
  `sname` varchar(100) NOT NULL DEFAULT '' COMMENT '公众号名称',
  `wishing` varchar(100) NOT NULL DEFAULT '' COMMENT '祝福语',
  `actname` varchar(100) NOT NULL DEFAULT '' COMMENT '红包活动名称',
  `logo` varchar(255) NOT NULL DEFAULT '' COMMENT 'logo',
  `hbwishing` varchar(100) DEFAULT '' COMMENT '红包祝福语',
  `hbactname` varchar(100) DEFAULT '' COMMENT '红包活动',
  `hbremark` varchar(150) DEFAULT '' COMMENT '红包描述',
  `createtime` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_hb_award` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `fansID` int(11) DEFAULT '0',
  `from_user` varchar(50) DEFAULT '0' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `awardname` varchar(50) DEFAULT '' COMMENT '描述',
  `prizetype` varchar(10) DEFAULT '' COMMENT '类型',
  `awardsimg` varchar(200) NOT NULL COMMENT '奖品图片',
  `prize` int(11) DEFAULT '0' COMMENT '奖品ID',
  `credit` decimal(11,2) DEFAULT '0.00' COMMENT '红包金额',
  `createtime` int(10) DEFAULT '0',
  `consumetime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_fansID` (`fansID`),
  KEY `indx_prize` (`prize`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_createtime` (`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_hb_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '发红包人openid',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `actual_money` decimal(11,2) DEFAULT '0.00' COMMENT '实际金额',
  `money` decimal(11,2) DEFAULT '0.00' COMMENT '下发金额',
  `counter` varchar(15) NOT NULL DEFAULT '' COMMENT '手续费',
  `hbnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '红包个数',
  `desknum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '桌号',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  `usesnum` int(10) DEFAULT '0',
  `usemoney` decimal(11,2) DEFAULT '0.00',
  `says` varchar(250) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_hb_setting` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `isfanshb` int(3) unsigned NOT NULL COMMENT '启用',
  `hb_minmoney` decimal(11,2) DEFAULT '0.01' COMMENT '最小金额',
  `hb_manmoney` decimal(11,2) DEFAULT '0.00' COMMENT '最大金额',
  `counter` decimal(11,2) DEFAULT '6.00' COMMENT '手续费',
  `hbtype` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '下发类型',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_isfanshb` (`isfanshb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_jiabing` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `pid` int(2) unsigned DEFAULT '0' COMMENT '排序',
  `rulename` varchar(255) NOT NULL COMMENT '活动规则',
  `uniacid` int(11) DEFAULT '0',
  `name` varchar(50) DEFAULT '',
  `description` varchar(600) DEFAULT '',
  `avatar` varchar(255) DEFAULT '',
  `img` varchar(255) DEFAULT '',
  `createtime` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可以用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_jiequan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `appid` varchar(255) DEFAULT '',
  `appsecret` varchar(255) DEFAULT '',
  `appid_share` varchar(255) DEFAULT '',
  `appsecret_share` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_messages` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) DEFAULT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `from_user` varchar(50) DEFAULT '' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `for_nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '被霸屏人昵称',
  `word` varchar(600) DEFAULT '',
  `wordimg` varchar(250) DEFAULT '',
  `status` tinyint(1) DEFAULT '0',
  `is_back` tinyint(1) DEFAULT '0',
  `is_xy` tinyint(1) DEFAULT '0',
  `is_bp` tinyint(1) DEFAULT '0' COMMENT '0未显示，1显示',
  `type` tinyint(1) DEFAULT '0' COMMENT '0普通，1霸屏，2打赏，3红包，4视频，5为人霸屏，6表白,7礼物',
  `is_bpshow` tinyint(1) DEFAULT '0',
  `gift` int(11) unsigned NOT NULL DEFAULT '0',
  `gift_id` int(11) unsigned NOT NULL DEFAULT '0',
  `bptime` int(11) unsigned NOT NULL DEFAULT '0',
  `says` varchar(300) DEFAULT '',
  `createtime` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_mp4` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `vodio_bg1` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景1',
  `vodio_bg2` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景2',
  `vodio_bg3` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景3',
  `vodio_bg4` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景4',
  `vodio_bg5` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景5',
  `vodio_bg6` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景6',
  `vodio_bg7` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景7',
  `vodio_bg8` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景8',
  `vodio_bg9` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景9',
  `vodio_bg10` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景10',
  `vodio_bg11` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景11',
  `vodio_bg12` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景12',
  `vodio_bg13` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景13',
  `vodio_bg15` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景15',
  `vodio_bg16` varchar(255) NOT NULL DEFAULT '' COMMENT '视频背景16',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_notifications` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `status` int(3) unsigned NOT NULL COMMENT '启用',
  `m_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `s_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `p_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `n_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `l_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `g_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `i_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `f_templateid` varchar(50) DEFAULT '' COMMENT '通知管理员模版消息',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_pair_combination` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(11) DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `one_openid` varchar(50) NOT NULL DEFAULT '' COMMENT '配对人openid',
  `other_openid` varchar(50) NOT NULL DEFAULT '' COMMENT '配对人对方openid',
  `one_nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '配对人微信昵称',
  `other_nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '配对人对方微信昵称',
  `one_avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '配对人微信头像',
  `other_avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '配对人对方微信头像',
  `pair` int(10) DEFAULT '0' COMMENT '第几对',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  PRIMARY KEY (`id`),
  KEY `idx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_password` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `pwid` varchar(50) NOT NULL DEFAULT '' COMMENT '口令ID',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
  `visitorstime` int(10) unsigned NOT NULL COMMENT '访问时间',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_pay_order` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `orderid` varchar(30) DEFAULT '0' COMMENT '订单单号',
  `transid` varchar(30) DEFAULT '0' COMMENT '微信支付单号',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT 'openid',
  `from_realname` varchar(50) NOT NULL DEFAULT '' COMMENT '名字',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `pay_ip` varchar(15) NOT NULL DEFAULT '' COMMENT '支付IP',
  `pay_addr` varchar(50) NOT NULL DEFAULT '' COMMENT '地理位置',
  `pay_total` decimal(11,2) DEFAULT '0.00' COMMENT '支付金额',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '下单未付款1已付款2已关闭3',
  `psy_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0表示报名，1表示打赏，2表示霸屏',
  `pay_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0表示报名，1表示打赏，2表示霸屏',
  `isadmin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否是管理员订单',
  `sex` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `fansid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '签到fansID',
  `createtime` int(11) unsigned NOT NULL COMMENT '创建时间',
  `paytime` int(11) unsigned NOT NULL COMMENT '支付时间',
  `bptime` int(11) unsigned NOT NULL COMMENT '霸屏时间',
  `message` varchar(150) NOT NULL DEFAULT '' COMMENT '霸屏留言',
  `wordimg` varchar(250) DEFAULT '' COMMENT '霸屏图片',
  `closetime` int(11) unsigned NOT NULL COMMENT '关闭时间',
  `transaction_id` varchar(150) DEFAULT '',
  `pay_status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_status` (`status`),
  KEY `indx_pay_total` (`pay_total`),
  KEY `indx_transid` (`transid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_pici` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `pici` varchar(10) DEFAULT '' COMMENT '批次',
  `rulename` varchar(50) DEFAULT NULL COMMENT '适用规则名称',
  `codenum` int(11) DEFAULT '0' COMMENT '口令数量',
  `is_qrcode` int(11) DEFAULT '0' COMMENT '是否生成二维码',
  `is_qrcode2` int(11) DEFAULT '0' COMMENT '是否生成永久二维码',
  `createtime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_pici` (`pici`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_prize` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `turntable` int(3) unsigned NOT NULL COMMENT '类型，现场抽奖1，抢红包2',
  `sort` int(3) unsigned NOT NULL COMMENT '奖品排序',
  `prizename` varchar(50) NOT NULL COMMENT '奖品名称',
  `couponid` varchar(255) NOT NULL COMMENT '微信卡券ID',
  `awardspro` double DEFAULT '0' COMMENT '奖品概率',
  `awardstotal` int(10) NOT NULL COMMENT '奖品数量',
  `prizedraw` int(10) NOT NULL COMMENT '中奖数量',
  `awardsimg` varchar(255) NOT NULL COMMENT '奖品图片',
  `prizetxt` text NOT NULL COMMENT '奖品说明',
  `credit` int(10) NOT NULL COMMENT '金额',
  `credit2` int(10) NOT NULL COMMENT '金额2',
  `jifen` int(10) NOT NULL COMMENT '积分',
  `jifen2` int(10) NOT NULL COMMENT '积分2',
  `ptype` tinyint(1) DEFAULT '0' COMMENT '奖项类型',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `title` varchar(100) DEFAULT '',
  `mobtitle` varchar(100) DEFAULT '',
  `description` varchar(255) DEFAULT '',
  `liucheng` text NOT NULL COMMENT '活动流程',
  `start_picurl` varchar(255) DEFAULT '',
  `backpicurl` varchar(255) DEFAULT '',
  `mobqhbbg` varchar(255) DEFAULT '',
  `kaimubg` varchar(255) DEFAULT '',
  `bimubg` varchar(255) DEFAULT '',
  `mobpicurl` varchar(255) DEFAULT '',
  `backcolor` varchar(255) DEFAULT '',
  `bottomcolor` varchar(255) DEFAULT '',
  `bottomwordcolor` varchar(255) DEFAULT '',
  `isshow` tinyint(1) DEFAULT '0',
  `xf_condition` tinyint(1) DEFAULT '0',
  `show_type` tinyint(1) DEFAULT '0',
  `ziliao` tinyint(1) DEFAULT '0',
  `start_hour` int(10) DEFAULT '0',
  `end_hour` int(2) DEFAULT '0',
  `is_openbbm` tinyint(1) DEFAULT '0',
  `adpic` varchar(255) DEFAULT '',
  `adpicurl` varchar(255) DEFAULT '',
  `ten_time` varchar(255) DEFAULT '',
  `total_num` int(11) DEFAULT '0' COMMENT '总获奖人数(自动加)',
  `award_times` int(11) DEFAULT '0',
  `password` varchar(50) DEFAULT '',
  `most_num_times` int(11) DEFAULT '0',
  `most_money` int(11) DEFAULT '0',
  `tx_most` int(11) DEFAULT '0',
  `is_show_prize` int(11) DEFAULT '0',
  `is_show_prize_num` int(11) DEFAULT '0',
  `up_qrcode` varchar(255) DEFAULT '',
  `copyright` varchar(20) DEFAULT '',
  `tiemadpic` varchar(255) DEFAULT '',
  `timenum` int(10) DEFAULT '0',
  `timeadurl` varchar(255) DEFAULT '0',
  `viewnum` int(11) DEFAULT '0' COMMENT '浏览次数',
  `fansnum` int(11) DEFAULT '0' COMMENT '参与人数',
  `createtime` int(10) DEFAULT '0',
  `share_acid` int(10) DEFAULT '0',
  `qjbpic` varchar(225) NOT NULL COMMENT '按钮2文字',
  `share_imgurl` varchar(255) NOT NULL COMMENT '分享朋友或朋友圈图',
  `share_title` varchar(200) DEFAULT '',
  `share_desc` varchar(300) DEFAULT '',
  `share_type` tinyint(1) DEFAULT '0',
  `is3ddaojishi` tinyint(1) DEFAULT '0',
  `daojishinum` int(2) DEFAULT '0',
  `registurl` varchar(300) DEFAULT '',
  `mybb_url` varchar(300) DEFAULT '',
  `gl_openid` varchar(300) DEFAULT '',
  `daojishimusic` varchar(300) DEFAULT '',
  `hb_lose_openid` varchar(50) DEFAULT '',
  `noip_url` varchar(300) DEFAULT '',
  `weid` int(10) NOT NULL,
  `picture` varchar(255) NOT NULL COMMENT '活动图片',
  `rules` text NOT NULL COMMENT '规则',
  `headpic` varchar(255) DEFAULT NULL COMMENT '头部图片',
  `headurl` varchar(255) DEFAULT NULL COMMENT '按钮2链接',
  `share_url` varchar(255) DEFAULT NULL COMMENT '按钮2链接',
  `panzi` varchar(255) DEFAULT NULL COMMENT '按钮1链接',
  `zhuanfaimg` varchar(255) DEFAULT NULL COMMENT '规则图片',
  `registimg` varchar(255) DEFAULT NULL,
  `loginpassword` varchar(30) DEFAULT '',
  `qrcodedec` varchar(50) DEFAULT '',
  `ismessage` tinyint(1) DEFAULT '0' COMMENT '是否开启消息墙',
  `isckmessage` tinyint(1) DEFAULT '0' COMMENT '是否需要审核消息',
  `isopenimg` tinyint(1) DEFAULT '0' COMMENT '是否开启图片自动放大',
  `isqd` tinyint(1) DEFAULT '0' COMMENT '是否开启3D签到墙',
  `is_award` tinyint(1) DEFAULT '0' COMMENT '是否开启中奖消息推送',
  `qdthemes` tinyint(1) DEFAULT '0' COMMENT '3D签到墙默认头像显示模式',
  `isqdthemes` tinyint(1) DEFAULT '0' COMMENT '3D签到墙默认显示模式',
  `qdshow` tinyint(1) DEFAULT '0' COMMENT '3D签到墙最近签到人员的显示模式',
  `ischoujiang` tinyint(1) DEFAULT '0' COMMENT '是否开启现场抽奖',
  `iscjnum` tinyint(1) DEFAULT '0' COMMENT '同一个人中奖数量',
  `isqhb` tinyint(1) DEFAULT '0' COMMENT '是否开启抢红包',
  `isqhbshow` tinyint(1) DEFAULT '0' COMMENT '抢红包是否开始',
  `jiabintitle` varchar(100) DEFAULT '' COMMENT '嘉宾墙顶部标题',
  `isjiabin` tinyint(1) DEFAULT '0' COMMENT '是否开启嘉宾墙',
  `is_showjiabin` tinyint(1) DEFAULT '0' COMMENT '是否手机端显示嘉宾',
  `jbtop_url` varchar(300) DEFAULT '' COMMENT '嘉宾手机顶部图片',
  `lose_hb` text NOT NULL,
  `allowip` text NOT NULL,
  `isallowip` tinyint(2) DEFAULT '0',
  `hbpici` int(4) DEFAULT '0',
  `tp_starttime` int(11) DEFAULT '0' COMMENT '投票开始时间',
  `tp_endtime` int(11) DEFAULT '0' COMMENT '投票结束时间',
  `tp_times` int(10) DEFAULT '1' COMMENT '每人投票次数',
  `tpbg_voice` varchar(300) DEFAULT '' COMMENT '投票墙背景音乐',
  `tpbg_url` varchar(300) DEFAULT '' COMMENT '投票墙背景图',
  `tptop_url` varchar(300) DEFAULT '' COMMENT '投票手机顶部图片',
  `toupiaotitle` varchar(100) DEFAULT '' COMMENT '投票墙顶部标题',
  `istoupiao` tinyint(1) DEFAULT '0' COMMENT '是否开启投票墙',
  `bm_starttime` int(11) DEFAULT '0' COMMENT '报名开始时间',
  `bm_endtime` int(11) DEFAULT '0' COMMENT '报名结束时间',
  `bm_pnumber` int(10) DEFAULT '0' COMMENT '报名人数限制',
  `isbaoming` tinyint(1) DEFAULT '0' COMMENT '是否开启报名',
  `isbaoming_pay` tinyint(1) DEFAULT '0' COMMENT '是否开启报名支付',
  `isbaoming_paymoney` int(10) DEFAULT '0' COMMENT '报名费用',
  `ad_link` varchar(300) DEFAULT '' COMMENT '支付成功后跳转页面',
  `3dlogo` varchar(600) DEFAULT '' COMMENT '3dlogo文字签到',
  `3dlogo1` varchar(300) DEFAULT '' COMMENT '3dlogo图片签到',
  `3dlogo2` varchar(300) DEFAULT '' COMMENT '3dlogo图片签到',
  `3dlogo3` varchar(300) DEFAULT '' COMMENT '3dlogo图片签到',
  `k_templateid` varchar(50) DEFAULT '' COMMENT '抽奖中奖模版消息',
  `isyyy` tinyint(1) DEFAULT '0' COMMENT '是否开启',
  `is_realname` tinyint(1) DEFAULT '0' COMMENT '是否开启',
  `is_b_share` int(11) DEFAULT '0' COMMENT '是否允许分享',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_toupiao` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `pid` int(2) unsigned DEFAULT '0' COMMENT '排序',
  `rulename` varchar(255) NOT NULL COMMENT '活动规则',
  `uniacid` int(11) DEFAULT '0',
  `get_num` int(11) DEFAULT '0' COMMENT '获得票数',
  `number` int(11) DEFAULT '0' COMMENT '编号',
  `starttime` int(11) DEFAULT '0' COMMENT '开始时间',
  `endtime` int(11) DEFAULT '0' COMMENT '结束时间',
  `back_time` int(11) DEFAULT '0' COMMENT '投票倒计时',
  `name` varchar(50) DEFAULT '',
  `description` varchar(600) DEFAULT '',
  `avatar` varchar(255) DEFAULT '',
  `img` varchar(255) DEFAULT '',
  `createtime` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可以用',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_tp_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '投票人openid',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `toupiaoip` varchar(15) NOT NULL DEFAULT '' COMMENT '投票ID',
  `tp_number` varchar(15) NOT NULL DEFAULT '' COMMENT '投票编号',
  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
  `visitorstime` int(10) unsigned NOT NULL COMMENT '投票时间',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '投票次数',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_fromuser` (`toupiaoip`),
  KEY `indx_tp_number` (`tp_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_whyerror` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `money` varchar(50) NOT NULL DEFAULT '' COMMENT '失败的金额',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  `why_error` text NOT NULL COMMENT '奖品说明',
  PRIMARY KEY (`id`),
  KEY `idx_uniacid` (`uniacid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_xyhm` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `turntable` int(3) unsigned NOT NULL COMMENT '类型，幸运号码1，幸运手机号2',
  `pici` int(3) unsigned NOT NULL COMMENT '排序',
  `number` text NOT NULL COMMENT '号码',
  `createtime` int(11) DEFAULT '0' COMMENT '时间',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_turntable` (`turntable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_xyhreply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `is_xyh` tinyint(1) unsigned NOT NULL COMMENT '是否开启幸运好',
  `is_xysjh` tinyint(1) unsigned NOT NULL COMMENT '是否开启幸运手机号',
  `xysjh_type` tinyint(1) unsigned NOT NULL COMMENT '幸运手机号显示方式',
  `xyh_bg` varchar(255) NOT NULL COMMENT '幸运号背景',
  `xysjh_bg` varchar(255) NOT NULL COMMENT '幸运手机号背景',
  `xyh_banner` varchar(255) NOT NULL COMMENT '幸运号标题',
  `xysjh_banner` varchar(255) NOT NULL COMMENT '幸运手机号标题',
  `xyh_music` varchar(255) NOT NULL COMMENT '幸运号背景音乐',
  `xysjh_music` varchar(255) NOT NULL COMMENT '幸运手机号手机背景音乐',
  `xyh_lottery` text NOT NULL COMMENT '幸运号内定',
  `xysjh_lottery` text NOT NULL COMMENT '幸运手机号内定',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_is_xyh` (`is_xyh`),
  KEY `indx_is_xysjh` (`is_xysjh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_xysreply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `isxys` tinyint(1) DEFAULT '0' COMMENT '是否开启许愿树活动',
  `xys_bg` varchar(300) DEFAULT '' COMMENT '背景图片',
  `xys_mbg` varchar(300) DEFAULT '' COMMENT '手机端背景图片',
  `xys_music` varchar(300) DEFAULT '' COMMENT '背景音乐',
  `xys_banner` varchar(300) DEFAULT '' COMMENT '顶部图片',
  `xys_backcolor` varchar(255) DEFAULT '',
  `pair_music` varchar(300) DEFAULT '' COMMENT '背景音乐',
  `pair_backcolor` varchar(300) DEFAULT '',
  `is_sex` tinyint(1) DEFAULT '0' COMMENT '是否开启性别填写',
  `is_pair` tinyint(1) DEFAULT '0' COMMENT '是否开启对对碰活动',
  `pair_bg` varchar(300) DEFAULT '' COMMENT '对对碰背景图片',
  `pair_banner` varchar(300) DEFAULT '' COMMENT '顶部图片',
  `is_turntable` tinyint(1) DEFAULT '0' COMMENT '是否开启大转盘活动',
  `is_meg` tinyint(1) DEFAULT '0' COMMENT '是否消息推送',
  `turntable_bg` varchar(300) DEFAULT '' COMMENT '对对碰背景图片',
  `turntable_banner` varchar(300) DEFAULT '' COMMENT '顶部图片',
  `turntable_music` varchar(300) DEFAULT '' COMMENT '背景音乐',
  `createtime` int(11) DEFAULT '0' COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_yyyreply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `isyyy` tinyint(1) DEFAULT '0' COMMENT '是否开启摇一摇活动',
  `pici` int(4) DEFAULT '0' COMMENT '活动批次',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '摇一摇活动是否进行中，0为还没开始，1为正在进行中，2为已经结束',
  `yyy_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否活动开始就不能参加，0不限制，1开始不能参加',
  `yyy_mannum` int(10) NOT NULL DEFAULT '0' COMMENT '活动人数限制，0表示不限制',
  `yyy_maxnum` int(10) NOT NULL DEFAULT '0' COMMENT '摇的最大次数',
  `yyy_bg` varchar(300) DEFAULT '' COMMENT '背景图片',
  `yyy_pdbg` varchar(300) DEFAULT '' COMMENT '背景图片',
  `yyy_mbg` varchar(300) DEFAULT '' COMMENT '手机端背景图片',
  `yyy_myyybg` varchar(300) DEFAULT '' COMMENT '手机端背景图片',
  `yyy_music` varchar(300) DEFAULT '' COMMENT '背景音乐',
  `yyy_banner` varchar(300) DEFAULT '' COMMENT '顶部图片',
  `yyy_maimg` varchar(300) DEFAULT '' COMMENT '图标类似，头像前面的图标，支持gif动画',
  `createtime` int(11) DEFAULT '0' COMMENT '每次批摇的时间',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `ims_haoman_dpm_yyyuser` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `pici` int(4) DEFAULT '0' COMMENT '活动批次',
  `from_user` varchar(50) DEFAULT '' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `point` int(10) NOT NULL DEFAULT '0' COMMENT '摇的数量',
  `createtime` int(11) DEFAULT '0' COMMENT '首次摇的时间',
  `endtime` int(11) DEFAULT '0' COMMENT '摇完次数的时间',
  `is_back` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_from_user` (`from_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
EOF;
pdo_run($sql);
